### ISSUE TITLE
Remove dependencies on resources and libs directories

### ISSUE THREAD

**Issue by jonathan-m-phillips** [jonathan-m-phillips/ASHE_Automated-Software-Hardening-for-Entrypoints#13]
We should remove the dependencies in the resources and libs directories so we do not need to add them to the compile and execution commands.

The issue with this is that we want to specifically use the Checker Framework on the minimized code after ASHE has already been running. Familiarity with Gradle is a minor blocker and will take some investigation.

**Comment by kelloggm** [comment]
From https://github.com/jonathan-m-phillips/ASHE_Automated-Software-Hardening-for-Entrypoints/pull/9#discussion_r1399571024:
Invoking the CF programmatically might be tricky. What I would do is something like the following:
* add the CF as a dependency in the Gradle file (i.e., here). That way it will be tracked appropriate by Gradle.
* somehow force Gradle to actually download the CF's jar from Maven Central before running ASHE. I'm not exactly sure how to do that, but it might be that having it as a dependency (even if it's not actually used in the Java code) is enough. Or, we might need to explicitly make "download the CF" a dependency of some gradle task. We'll have to experiment a bit with this.
* when gradle downloads a dependency, it puts that dependency in a predictable location under ~/.m2/repository/. We can use that to actually find the appropriate CF version in the code that we use to invoke it. Note that the version number is in the path, so we'll need to make sure we account for that, too.

**Comment by jonathan-m-phillips** [comment]
Gradle does not use .m2/repository for dependencies, such as Maven does. In order to access the dependencies via Gradle, we would need to navigate to .gradle/caches/modules-2/files-2.1/org.checkerframework/checker/3.38.0/your_own_hash_here/checker-3.38.0.jar. This will almost certainly not work since a new hash will be generated for each user's own environment. We could hack a way around it, where we step into the second directory in /3.38.0/hash_here, but there is no guarantee that would always hold the jar, and that seems flawed.

In a Maven project, the dependencies/jars are always free to access as @kelloggm suggested. If using Maven, it would be as simple as getting the path of user.home/.m2/repository and working down the directories.

I have come up with a solution - although not the best - it reduces the need for storing the libs/ directory in the repository. Within build.gradle, we can create a task to create a checkerframework directory and store the jars. build/libs is where our snapshot jar is stored, so within here, we can create a checkerframework/ directory. For example, build/libs/checkerframework/jars_stored_here. Other than the initial build, this will not change any of the current logic and can be seen as a minor workaround.

PR #34 has been created to implement this.

**Comment by jonathan-m-phillips** [comment]
Fixed with PR #34. Closing issue!
