### ISSUE TITLE
Add ability to dryrun to AsheAutomation

### ISSUE THREAD

**Issue by kelloggm** [jonathan-m-phillips/ASHE_Automated-Software-Hardening-for-Entrypoints#30]
It would be very useful if AsheAutomation had a mode that does not actually invoke the LLM, but instead:
* checks out the target projects
* runs specimin to set up the call to the LLM
* uses the "testing" mode in #28 to mock the call to the LLM, so that we don't actually spend $$

This mode will be very useful for testing that Ashe/AsheAutomation work well, and also allow us to detect any bugs in specimin on programs that we're interested in. More broadly, it'll be useful to users so that they can be confident that a run of ASHE will get to the stage where calls to the LLM (which cost money) will actually be useful.

**Comment by jonathan-m-phillips** [comment]
Completed with #32. Closing issues.
