### ISSUE TITLE
Inconsistency in documentation/implementation for `OpenAiRequestHandler#apiResponse`

### ISSUE THREAD

**Issue by jyoo980** [jonathan-m-phillips/ASHE_Automated-Software-Hardening-for-Entrypoints#38]
Hi,

I'm currently working on adding support for Google's LLMs, but I came across an inconsistency between the implementation of `OpenAiRequestHandler#apiResponse`:

The Javadoc for this method has the following `throws` clauses:

```java
/**
 * ...
 * @throws IOException              if an I/O error occurs, or if the response is not received within 60 seconds
 * ...
 * @throws TimeoutException         if waiting for the CompletableFuture times out
 */
```

The implementation leads me to believe that an `IOException` is thrown and a `TimeoutException` is actually never thrown in practice:

https://github.com/jonathan-m-phillips/ASHE_Automated-Software-Hardening-for-Entrypoints/blob/d7c703e1a20d5a7a3308b11195d211fc6693b04b/src/main/java/edu/njit/jerse/ashe/llm/openai/OpenAiRequestHandler.java#L125-L127

Is this intended? If not, should either the documentation or the implementation be updated? I am happy to make the change, if needed.

**Comment by jonathan-m-phillips** [comment]
Hello James,

Great catch! This was an accident and should be changed. I think it is most reasonable to log the error message and then throw either a new TimeoutException with the same error message, or to throw the one caught.
Example:
String errorMessage = "your message here";
LOGGER.fatal(errorMessage);
throw new TimeoutException(errorMessage, e);

Additionally, the documentation should be changed.

Thanks,
Jonathan
